### ISSUE TITLE
Not Work URL

### ISSUE THREAD

**Issue by algabe** [bnrubin/Supytube#6]
ERROR 2015-05-10T09:48:18 Uncaught exception in Supytube.__call__:
Traceback (most recent call last):
  File "/home/algabe/local/lib/python2.7/site-packages/supybot/log.py", line 361, in m
    return f(self, *args, **kwargs)
  File "/home/algabe/local/lib/python2.7/site-packages/supybot/irclib.py", line 126, in __call__
    method(irc, msg)
  File "/home/algabe/local/bin/plugins/Supytube/plugin.py", line 94, in doPrivmsg
    reply = 'Title: {0}, Views {1}, Rating: {2}'.format(title, views, rating)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2665' in position 27: ordinal not in range(128)
ERROR 2015-05-10T09:48:18 Exception id: 0x1ffe4
Exception in thread Thread #4 (for snarfing https://www.youtube.com/watch?v=0xJcCUROfSc):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/algabe/local/lib/python2.7/site-packages/supybot/commands.py", line 162, in run
    super(UrlSnarfThread, self).run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/algabe/local/lib/python2.7/site-packages/supybot/commands.py", line 213, in doSnarf
    f(self, irc, msg, match, *L, **kwargs)
  File "/home/algabe/local/lib/python2.7/site-packages/supybot/plugins/Web/plugin.py", line 96, in newf
    pn=self.name(), cn=f.__name__)
  File "/home/algabe/local/lib/python2.7/site-packages/supybot/commands.py", line 89, in process
    if conf.disableMultiprocessing:
AttributeError: 'module' object has no attribute 'disableMultiprocessing'

**Comment by bnrubin** [comment]
Also, it seems that your supybot install is in a weird state, you shouldn't be seeing that AttributeError.  Take a look at http://echelog.com/logs/browse/supybot/1415314800 for some possible solutions.
